name: jft_exam_app
description: JFT Simulation Exam App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  audioplayers: ^5.2.1
  google_mobile_ads: ^5.0.0  # ✅ ဒီမှာ ပြောင်းပါ
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/jft1-q1.jpg
    - assets/images/jft1-q2.jpg
    - assets/images/jft1-q3.jpg
    - assets/images/jft1-q4.jpg
    - assets/images/jft1-q5.jpg
    - assets/images/jft1-q6.jpg
    - assets/images/jft1-q7.jpg
    - assets/images/jft1-q8.jpg
    - assets/images/jft1-q9.jpg
    - assets/images/jft1-q10.jpg
    - assets/images/jft1-q11.jpg
    - assets/images/jft1-q12.jpg
    - assets/images/jft1-q13.jpg
    - assets/images/jft1-q14.jpg
    - assets/images/jft1-q15.jpg
    - assets/images/jft1-q16.jpg
    - assets/images/jft1-q17.jpg
    - assets/images/jft1-q18.jpg
    - assets/images/jft1-q19.jpg
    - assets/images/jft1-q20.jpg
    - assets/images/jft1-q21.jpg
    - assets/images/jft1-q22.jpg
    - assets/images/jft1-q23.jpg
    - assets/images/jft2-q1.jpg
    - assets/images/jft2-q2.jpg
    - assets/images/jft2-q3.jpg
    - assets/images/jft2-q4.jpg
    - assets/images/jft2-q5.jpg
    - assets/images/jft2-q6.jpg
    - assets/images/jft2-q7.jpg
    - assets/images/jft2-q8.jpg
    - assets/images/jft2-q9.jpg
    - assets/images/jft2-q10.jpg
    - assets/images/jft2-q11.jpg
    - assets/images/jft2-q12.jpg
    - assets/images/jft2-q13.jpg
    - assets/images/jft2-q14.jpg
    - assets/images/jft2-q15.jpg
    - assets/images/jft2-q16.jpg
    - assets/images/jft2-q17.jpg
    - assets/images/jft2-q18.jpg
    - assets/images/jft2-q19.jpg
    - assets/images/jft2-q20.jpg
    - assets/images/jft2-q21.jpg
    - assets/images/jft2-q22.jpg
    - assets/images/jft2-q23.jpg
    - assets/audio/jft-q1.mp3
    - assets/audio/jft-q2.mp3
    - assets/audio/jft-q3.mp3
    - assets/audio/jft-q4.mp3
    - assets/audio/jft-q5.mp3
    - assets/audio/jft-q6.mp3
    - assets/audio/jft-q7.mp3
    - assets/audio/jft-q8.mp3
    - assets/audio/jft-q9.mp3
    - assets/audio/jft-q10.mp3
    - assets/audio/jft2-q1.mp3
    - assets/audio/jft2-q2.mp3
    - assets/audio/jft2-q3.mp3
    - assets/audio/jft2-q4.mp3
    - assets/audio/jft2-q5.mp3
    - assets/audio/jft2-q6.mp3
    - assets/audio/jft2-q7.mp3
    - assets/audio/jft2-q8.mp3
    - assets/audio/jft2-q9.mp3
    - assets/audio/jft2-q10.mp3
